name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      # Checkout the repository
      - name: Checkout repository code
        uses: actions/checkout@v3
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Config version of image
      - name: Set up Docker Tag
        run: |
          # read the current version from the VERSION file
          version=$(cat VERSION)
          echo "Current version: v$version"
          next_version=$((version + 1))
          echo $next_version > VERSION
          echo "next_version=v$next_version" >> $GITHUB_ENV
      # Build docker image
      - name: Build Docker image
        run: |  
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-test:v${{ env.next_version }} .
      # Push docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-test:v${{ env.next_version }}
      # Update version file
      - name: Commit updated VERSION file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to v${{ env.next_version }}"
          git push